name: Generate Docs

on:
  push:
    branches:
      - main
      - DocsWorkflow
    paths:
      - pubspec.yaml
      - .github/workflows/docs.yml

jobs:
  cancel-previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  docs:
    name: Generate docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.STRIVEBOT_TOKEN }}

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare branch
        run: |
          git config user.name strivebot
          git checkout api-docs
          git merge origin/main

      - run: flutter pub get

      - name: Create docs
        run: ./createDocs.sh

      - name: Update branch
        run: |
          git add .
          git commit -m "Update generated documentation" && git push || true
